<?php if ($this->getTotals()): ?>
    <table class="gtotals">
    <tfoot>
    <?php $_colspan = 2; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
        <tr>
            <td class="a-right" colspan="<?php echo $_colspan; ?>">
                <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
            </td>
            <td class="a-right">
                <small><?php echo $this->displayBaseGrandtotal() ?></small>
            </td>
        </tr>
    <?php endif?>
    </tfoot>
    </table>
    <p>By placing your order, you agree to <a href="https://www.glovida.com/terms-of-use/">TERMS OF USE</a> and  <a href="https://www.glovida.com/privacy-policy/">PRIVACY POLICY</a></p>
<?php endif; ?>
